function l(b,a,d,c){b.i.la(b.P,a,d,c,void 0)}function p(b,a,d,c){b.i.v?l(b,a,d,c):b.i.tb()._OnMessageFromDOM({type:"event",component:b.P,handler:a,dispatchOpts:c||null,data:d,responseId:null})}function q(b,a,d){b.i.h(b.P,a,d)}function aa(b,a){for(const [d,c]of a)q(b,d,c)}window.Ha=class{constructor(b,a){this.i=b;this.P=a}Ea(){}};window.kb=class{constructor(b){this.Sa=b;this.Gb=5;this.K=-1;this.da=-Infinity;this.Lb=()=>{this.K=-1;this.da=Date.now();this.R=!0;this.Sa();this.R=!1};this.Ta=this.R=!1}};
"use strict";function ba(b,a){const d=a.elementId,c=b.Ga(d,a);b.s.set(d,c);c.style.boxSizing="border-box";a.isVisible||(c.style.display="none");a=b.pa(c);a.addEventListener("focus",()=>{r(b,"elem-focused",d)});a.addEventListener("blur",()=>{r(b,"elem-blurred",d)});b.ba&&document.body.appendChild(c)}function ca(b,a){q(b,"get-element",d=>{const c=b.s.get(d.elementId);return a(c,d)})}function r(b,a,d){var c;c||(c={});c.elementId=d;l(b,a,c)}
window.cb=class extends self.Ha{constructor(b){super(b,"button");this.s=new Map;this.ba=!0;aa(this,[["create",a=>ba(this,a)],["destroy",a=>{a=a.elementId;const d=this.s.get(a);this.ba&&d.parentElement.removeChild(d);this.s.delete(a)}],["set-visible",a=>{this.ba&&(this.s.get(a.elementId).style.display=a.isVisible?"":"none")}],["update-position",a=>{if(this.ba){var d=this.s.get(a.elementId);d.style.left=a.left+"px";d.style.top=a.top+"px";d.style.width=a.width+"px";d.style.height=a.height+"px";a=a.fontSize;
null!==a&&(d.style.fontSize=a+"em")}}],["update-state",a=>{const d=this.s.get(a.elementId);this.na(d,a)}],["focus",a=>{const d=this.pa(this.s.get(a.elementId));a.focus?d.focus():d.blur()}],["set-css-style",a=>{const d=this.s.get(a.elementId),c=a.prop;a=a.val;c.startsWith("--")?d.style.setProperty(c,a):d.style[c]=a}],["set-attribute",a=>{this.s.get(a.elementId).setAttribute(a.name,a.val)}],["remove-attribute",a=>{this.s.get(a.elementId).removeAttribute(a.name)}]]);ca(this,a=>a)}Ga(){throw Error("required override");
}na(){throw Error("required override");}pa(b){return b}};"use strict";const t=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),u=/android/i.test(navigator.userAgent);let v=0;function w(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.Qb?new Promise(d=>{const c="c3_resolve_"+v;++v;self[c]=d;a.textContent=b.Ub+`\n\nself["${c}"]();`;document.head.appendChild(a)}):new Promise((d,c)=>{a.onload=d;a.onerror=c;a.src=b;document.head.appendChild(a)})}
let x=!1,y=!1;function da(){if(!x){try{new Worker("blob://",{get type(){y=!0}})}catch(b){}x=!0}return y}let z=new Audio;const ea={"audio/webm; codecs=opus":!!z.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!z.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!z.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!z.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!z.canPlayType("audio/mp4"),"audio/mpeg":!!z.canPlayType("audio/mpeg")};z=null;
async function fa(b){b=await A(b);return(new TextDecoder("utf-8")).decode(b)}function A(b){return new Promise((a,d)=>{const c=new FileReader;c.onload=e=>a(e.target.result);c.onerror=e=>d(e);c.readAsArrayBuffer(b)})}const B=[];let C=0;window.RealFile=window.File;const D=[],E=new Map,F=new Map;let ha=0;const G=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");G.push(b)};const I=new Set(["cordova","playable-ad","instant-games"]);let ia=!1;
window.ma=class b{constructor(a){this.v=a.Wb;this.U=null;this.m="";this.I=a.Tb;this.Z={};this.xa=this.L=null;this.ca=[];this.j=this.X=null;this.Xa=!1;this.S=null;this.H=-1;this.Kb=()=>this.Ab();this.$a=[];this.g=a.ab;this.va="file"===location.protocol.substr(0,4);!this.v||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&da()||(this.v=!1);if("playable-ad"===this.g||"instant-games"===this.g)this.v=!1;if("cordova"===this.g&&this.v)if(u){const d=/Chrome\/(\d+)/i.exec(navigator.userAgent);
d&&90<=parseInt(d[1],10)||(this.v=!1)}else this.v=!1;this.ea=this.B=null;"html5"!==this.g||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.h("runtime","cordova-fetch-local-file",d=>this.wb(d));this.h("runtime","create-job-worker",()=>this.xb());"cordova"===this.g?document.addEventListener("deviceready",()=>this.La(a)):this.La(a)}hb(){return t&&
"cordova"===this.g}ka(){const a=navigator.userAgent;return t&&I.has(this.g)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}fb(){return u}Ia(){return u&&I.has(this.g)}async La(a){"macos-wkwebview"===this.g&&this.Eb();if("playable-ad"===this.g){this.B=self.c3_base64files;this.ea={};await this.pb();for(let c=0,e=a.M.length;c<e;++c){var d=a.M[c];this.ea.hasOwnProperty(d)?a.M[c]={Qb:!0,Ub:this.ea[d]}:this.B.hasOwnProperty(d)&&(a.M[c]=URL.createObjectURL(this.B[d]))}}a.Sb?this.m=a.Sb:(d=location.origin,
this.m=("null"===d?"file:///":d)+location.pathname,d=this.m.lastIndexOf("/"),-1!==d&&(this.m=this.m.substr(0,d+1)));a.Yb&&(this.Z=a.Yb);d=new MessageChannel;this.U=d.port1;this.U.onmessage=c=>this._OnMessageFromRuntime(c.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(c=>this.zb(c));this.S=new self.ib(this);await ja(this.S);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((c,e)=>{window.AndroidFullScreen.immersiveMode(c,
e)})}catch(c){console.error("Failed to enter Android immersive mode: ",c)}this.v?await this.vb(a,d.port2):await this.ub(a,d.port2)}qa(a){a=this.Z.hasOwnProperty(a)?this.Z[a]:a.endsWith("/workermain.js")&&this.Z.hasOwnProperty("workermain.js")?this.Z["workermain.js"]:"playable-ad"===this.g&&this.B.hasOwnProperty(a)?this.B[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async ja(a,d,c){if(a.startsWith("blob:"))return new Worker(a,c);if("cordova"===this.g&&this.va)return a=await this.ia(c.Pb?
a:this.I+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),c);a=new URL(a,d);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),c)}return new Worker(a,c)}A(){return Math.max(window.innerWidth,1)}u(){return Math.max(window.innerHeight,1)}Ka(a){var d=this.m,c=location.href,e=this.A(),f=this.u(),g=window.devicePixelRatio,h=b.N(),k=a.cc,m=window.cr_previewImageBlobs||
this.B,n=window.cr_previewProjectFileBlobs,ua=window.cr_previewProjectFiles,va=window.ac||"";a=a.ab;var wa=(new URLSearchParams(self.location.search)).has("debug"),H=this.S;return{runtimeBaseUrl:d,previewUrl:c,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:k,previewImageBlobs:m,previewProjectFileBlobs:n,previewProjectFileSWUrls:ua,swClientId:va,exportType:a,isDebug:wa,ife:!!self.bc,jobScheduler:{inputPort:H.ua,outputPort:H.za,maxNumWorkers:H.Ib},supportedAudioFormats:ea,
opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.I+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.I+"opus.wasm.wasm",isFileProtocol:this.va,isiOSCordova:this.hb(),isiOSWebView:this.ka(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async vb(a,d){const c=this.qa(a.Xb);"preview"===this.g?(this.L=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((h,k)=>{const m=n=>{this.L.removeEventListener("message",m);n.data&&"ok"===n.data.type?h():
k()};this.L.addEventListener("message",m);this.L.postMessage({type:"construct-worker-init","import":(new URL(c,this.m)).toString()})})):this.L=await this.ja(c,this.m,{type:"module",name:"Runtime",Pb:!0});this.j=document.createElement("canvas");this.j.style.display="none";const e=this.j.transferControlToOffscreen();document.body.appendChild(this.j);window.c3canvas=this.j;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.Ca||[],g=a.M;f=await Promise.all(f.map(h=>this.F(h)));g=
await Promise.all(g.map(h=>this.F(h)));if("cordova"===this.g)for(let h=0,k=a.ha.length;h<k;++h){const m=a.ha[h],n=m[0];if(n===a.Ba||"scriptsInEvents.js"===n||n.endsWith("/scriptsInEvents.js"))m[1]=await this.F(n)}this.L.postMessage(Object.assign(this.Ka(a),{type:"init-runtime",isInWorker:!0,messagePort:d,canvas:e,workerDependencyScripts:f,engineScripts:g,projectScripts:a.ha,mainProjectScript:a.Ba,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[d,e,...ka(this.S)]);this.ca=D.map(h=>new h(this));
this.Ja();la(this.X);self.c3_callFunction=(h,k)=>{var m=this.X;return m.i.jb(m.P,{name:h,params:k})};"preview"===this.g&&(self.goToLastErrorScript=()=>this.la("runtime","go-to-last-error-script"))}async ub(a,d){this.j=document.createElement("canvas");this.j.style.display="none";document.body.appendChild(this.j);window.c3canvas=this.j;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.ca=D.map(g=>new g(this));this.Ja();var c=a.M.map(g=>"string"===typeof g?(new URL(g,this.m)).toString():
g);Array.isArray(a.Ca)&&c.unshift(...a.Ca);c=await Promise.all(c.map(g=>this.F(g)));await Promise.all(c.map(g=>w(g)));c=self.C3_ProjectScriptsStatus;const e=a.Ba,f=a.ha;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.F(h),await w(h),"preview"!==this.g||c[g]||this.Na(g,"main script did not run to completion")}catch(k){this.Na(g,k)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.F(h),await w(h);"preview"===this.g&&"object"!==typeof self.Zb.$b?(this.aa(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Ka(a),{isInWorker:!1,messagePort:d,canvas:this.j,runOnStartupFunctions:G}),la(this.X),this.Ma(),this.xa=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.xa,a))}Na(a,d){this.aa();console.error(`[Preview] Failed to load project main script (${a}): `,d);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Ma(){this.aa()}aa(){const a=
window.Nb;a&&(a.parentElement.removeChild(a),window.Nb=null)}async xb(){const a=await na(this.S);return{outputPort:a,transferables:[a]}}tb(){if(this.v)throw Error("not available in worker mode");return this.xa}la(a,d,c,e,f){this.U.postMessage({type:"event",component:a,handler:d,dispatchOpts:e||null,data:c,responseId:null},f)}jb(a,d){const c=ha++,e=new Promise((f,g)=>{F.set(c,{resolve:f,reject:g})});this.U.postMessage({type:"event",component:a,handler:"js-invoke-function",dispatchOpts:null,data:d,
responseId:c},void 0);return e}_OnMessageFromRuntime(a){const d=a.type;if("event"===d)return this.yb(a);if("result"===d)this.Bb(a);else if("runtime-ready"===d)this.Cb();else if("alert-error"===d)this.aa(),alert(a.message);else if("creating-runtime"===d)this.Ma();else throw Error(`unknown message '${d}'`);}yb(a){const d=a.component,c=a.handler,e=a.data,f=a.responseId;if(a=E.get(d))if(a=a.get(c)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${d}' handler '${c}':`,h);null!==f&&this.$(f,
!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.$(f,!0,h)).catch(h=>{console.error(`Rejection from '${d}' handler '${c}':`,h);this.$(f,!1,""+h)}):this.$(f,!0,g)}else console.warn(`[DOM] No handler '${c}' for component '${d}'`);else console.warn(`[DOM] No event handlers for component '${d}'`)}$(a,d,c){let e;c&&c.transferables&&(e=c.transferables);this.U.postMessage({type:"result",responseId:a,isOk:d,result:c},e)}Bb(a){const d=a.responseId,c=a.isOk;a=a.result;const e=F.get(d);c?e.resolve(a):
e.reject(a);F.delete(d)}h(a,d,c){let e=E.get(a);e||(e=new Map,E.set(a,e));if(e.has(d))throw Error(`[DOM] Component '${a}' already has handler '${d}'`);e.set(d,c)}static Da(a){if(D.includes(a))throw Error("DOM handler already added");D.push(a)}Ja(){for(const a of this.ca)if("runtime"===a.P){this.X=a;return}throw Error("cannot find runtime DOM handler");}zb(a){this.la("debugger","message",a)}Cb(){for(const a of this.ca)a.Ea()}static N(){return!!(document.fullscreenElement||document.webkitFullscreenElement||
document.mozFullScreenElement||ia)}static Pa(a){ia=!!a}Oa(){-1===this.H&&this.$a.length&&(this.H=requestAnimationFrame(this.Kb))}nb(){-1!==this.H&&(cancelAnimationFrame(this.H),this.H=-1)}Ab(){this.H=-1;for(const a of this.$a)a();this.Oa()}ra(){this.X.ra()}lb(){this.Xa=!0}eb(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}gb(a){return!this.eb(a)}async F(a){return"cordova"===this.g&&(a.startsWith("file:")||this.va&&this.gb(a))?(a.startsWith(this.m)&&(a=a.substr(this.m.length)),
a=await this.ia(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async wb(a){const d=a.filename;switch(a.as){case "text":return await this.bb(d);case "buffer":return await this.ia(d);default:throw Error("unsupported type");}}Fa(a){const d=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((c,e)=>{window.resolveLocalFileSystemURL(d,f=>{f.file(c,e)},e)})}async bb(a){a=await this.Fa(a);return await fa(a)}oa(){if(B.length&&!(8<=C)){C++;var a=B.shift();this.qb(a.filename,
a.Vb,a.Ob)}}ia(a){return new Promise((d,c)=>{B.push({filename:a,Vb:e=>{C--;this.oa();d(e)},Ob:e=>{C--;this.oa();c(e)}});this.oa()})}async qb(a,d,c){try{const e=await this.Fa(a),f=await A(e);d(f)}catch(e){c(e)}}Eb(){var a={type:"ready"};if("windows-webview2"===this.g)window.chrome.webview.postMessage(JSON.stringify(a));else if("macos-wkwebview"===this.g)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");}async pb(){const a=[];for(const [d,
c]of Object.entries(this.B))a.push(this.ob(d,c));await Promise.all(a)}async ob(a,d){if("object"===typeof d)this.B[a]=new Blob([d.str],{type:d.type}),this.ea[a]=d.str;else{let c=await this.sb(d);c||(c=this.rb(d));this.B[a]=c}}async sb(a){try{return await (await fetch(a)).blob()}catch(d){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",d),
null}}rb(a){a=this.Db(a);return this.mb(a.data,a.Rb)}Db(a){var d=a.indexOf(",");if(0>d)throw new URIError("expected comma in data: uri");var c=a.substring(d+1);d=a.substring(5,d).split(";");a=d[0]||"";const e=d[2];c="base64"===d[1]||"base64"===e?atob(c):decodeURIComponent(c);return{Rb:a,data:c}}mb(a,d){var c=a.length;let e=c>>2,f=new Uint8Array(c),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(c&=3;c--;)f[k]=
a.charCodeAt(k),++k;return new Blob([f],{type:d})}};"use strict";const J=self.ma;function oa(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const pa=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),K={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},qa={dispatchUserScriptEvent:!0},L={dispatchRuntimeEvent:!0};
function ra(b){return new Promise((a,d)=>{const c=document.createElement("link");c.onload=()=>a(c);c.onerror=e=>d(e);c.rel="stylesheet";c.href=b;document.head.appendChild(c)})}function sa(b){return new Promise((a,d)=>{const c=new Image;c.onload=()=>a(c);c.onerror=e=>d(e);c.src=b})}async function M(b){b=URL.createObjectURL(b);try{return await sa(b)}finally{URL.revokeObjectURL(b)}}
function ta(b){return new Promise((a,d)=>{let c=new FileReader;c.onload=e=>a(e.target.result);c.onerror=e=>d(e);c.readAsText(b)})}
async function xa(b,a,d){if(!/firefox/i.test(navigator.userAgent))return await M(b);var c=await ta(b);c=(new DOMParser).parseFromString(c,"image/svg+xml");const e=c.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await M(b)}e.setAttribute("width",a+"px");e.setAttribute("height",d+"px");c=(new XMLSerializer).serializeToString(c);b=new Blob([c],{type:"image/svg+xml"});return await M(b)}
function N(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const ya=new Set(["input","textarea","datalist","select"]),za=new Set(["canvas","body","html"]);function O(b){za.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Aa(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await M(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,d,c,e){b=await xa(b,a,d);const f=document.createElement("canvas");f.width=c;f.height=e;f.getContext("2d").drawImage(b,0,0,a,d);return f};
let P=!1;document.addEventListener("pause",()=>P=!0);document.addEventListener("resume",()=>P=!1);function la(b){b.Va=!0;b.wa=b.i.A();b.T=b.i.u()}async function Ba(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Ca(b){return await self.C3_GetSvgImageSize(b.blob)}
function Da(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}function Ea(b){self.setTimeout(()=>{b.Ua=!0},1E3);"cordova"===b.i.g?(document.addEventListener("pause",()=>Q(b,!0)),document.addEventListener("resume",()=>Q(b,!1))):document.addEventListener("visibilitychange",()=>Q(b,document.hidden));return{isSuspended:!(!document.hidden&&!P)}}
function Fa(b){b.Ra||(b.Ra=!0,window.addEventListener("deviceorientation",a=>{b.l||l(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},K)}),window.addEventListener("deviceorientationabsolute",a=>{b.l||l(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},K)}))}
function Ga(b){b.Qa||(b.Qa=!0,window.addEventListener("devicemotion",a=>{if(!b.l){var d=null,c=a.acceleration;c&&(d={x:c.x||0,y:c.y||0,z:c.z||0});c=null;var e=a.accelerationIncludingGravity;e&&(c={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});l(b,"devicemotion",{acceleration:d,accelerationIncludingGravity:c,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},K)}}))}async function Ia(b){await ra(b.url)}
function Ja(b,a){b.Wa=a.message;-1===b.ta&&(b.ta=setTimeout(()=>{b.ta=-1;const d=document.getElementById("exportToVideoMessage");d&&(d.textContent=b.Wa)},250))}function R(b){if(!b.l){var a=J.N();a&&"any"!==b.Aa&&Ka(b);l(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.A(),innerHeight:b.u()})}}function S(b,a){console.warn("[Construct] Fullscreen request failed: ",a);l(b,"fullscreenerror",{isFullscreen:J.N(),innerWidth:b.A(),innerHeight:b.u()})}
function Q(b,a){a?b.i.nb():b.i.Oa();l(b,"visibilitychange",{hidden:a})}function La(b,a,d){"Backspace"===d.key&&O(d);if(!b.l){var c=pa.get(d.code)||d.code;p(b,a,{code:c,key:d.key,which:d.which,repeat:d.repeat,altKey:d.altKey,ctrlKey:d.ctrlKey,metaKey:d.metaKey,shiftKey:d.shiftKey,timeStamp:d.timeStamp},K)}}
function T(b,a,d,c){b.l||oa(d)||p(b,a,{button:d.button,buttons:d.buttons,clientX:d.clientX,clientY:d.clientY+b.o,pageX:d.pageX,pageY:d.pageY+b.o,movementX:d.movementX||0,movementY:d.movementY||0,timeStamp:d.timeStamp},c)}function U(b){window!==window.top&&window.focus();Ma(b.target)&&document.activeElement&&!Ma(document.activeElement)&&document.activeElement.blur()}
function V(b,a,d){if(!b.l){if(b.W&&"pointermove"!==a){var c=b.W;c.R||(-1!==c.K&&(self.clearTimeout(c.K),c.K=-1),c.da=Date.now())}c=0;"mouse"===d.pointerType&&(c=b.V);p(b,a,{pointerId:d.pointerId,pointerType:d.pointerType,button:d.button,buttons:d.buttons,lastButtons:c,clientX:d.clientX,clientY:d.clientY+b.o,pageX:d.pageX,pageY:d.pageY+b.o,movementX:(d.movementX||0)+b.fa,movementY:(d.movementY||0)+b.ga,width:d.width||0,height:d.height||0,pressure:d.pressure||0,tangentialPressure:d.tangentialPressure||
0,tiltX:d.tiltX||0,tiltY:d.tiltY||0,twist:d.twist||0,timeStamp:d.timeStamp},K);b.fa=0;b.ga=0;"mouse"===d.pointerType&&(c="mousemove","pointerdown"===a?c="mousedown":"pointerup"===a&&(c="mouseup"),T(b,c,d,qa),b.V=d.buttons)}}
function W(b,a,d){if(!b.l&&!oa(d)){var c=b.V;"pointerdown"===a&&0!==c?a="pointermove":"pointerup"===a&&0!==d.buttons&&(a="pointermove");p(b,a,{pointerId:1,pointerType:"mouse",button:d.button,buttons:d.buttons,lastButtons:c,clientX:d.clientX,clientY:d.clientY+b.o,pageX:d.pageX,pageY:d.pageY+b.o,movementX:d.movementX||0,movementY:d.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:d.timeStamp},K);b.V=d.buttons;T(b,d.type,d,qa)}}
function X(b,a,d){if(!b.l)for(let c=0,e=d.changedTouches.length;c<e;++c){const f=d.changedTouches[c];p(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.o,pageX:f.pageX,pageY:f.pageY+b.o,movementX:d.movementX||0,movementY:d.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:d.timeStamp},
K)}}function Y(b,a,d){document.body.style.transform="";b.o=0;if(0<d){var c=document.activeElement;c&&(c=c.getBoundingClientRect(),a=(c.top+c.bottom)/2-(a-d)/2,a>d&&(a=d),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.o=a))}}function Na(b,a,d,c){const e=b.A(),f=b.u();b.J=-1;e!=a||f!=d?l(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:J.N()}):10>c&&Oa(b,e,f,c+1)}
function Oa(b,a,d,c){-1!==b.J&&clearTimeout(b.J);b.J=setTimeout(()=>Na(b,a,d,c),48)}
function Ka(b){b=b.Aa;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",a)}}
function Ma(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
J.Da(class extends self.Ha{constructor(b){super(b,"runtime");this.Ya=!0;this.Va=!1;this.J=-1;this.Aa="any";this.Qa=this.Ra=!1;this.D=null;this.l=!1;this.Wa="";this.ta=-1;this.G=this.W=null;this.ga=this.fa=0;this.Ua=!1;this.wa=b.A();this.T=b.u();this.o=this.Y=0;b.h("canvas","update-size",c=>{var e=this.i;e.Xa||(e=e.j,e.style.width=c.styleWidth+"px",e.style.height=c.styleHeight+"px",e.style.marginLeft=c.marginLeft+"px",e.style.marginTop=c.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",
c.displayScale),this.Ya&&(e.style.display="",this.Ya=!1))});b.h("runtime","invoke-download",c=>{const e=c.url;c=c.filename;const f=document.createElement("a"),g=document.body;f.textContent=c;f.href=e;f.download=c;g.appendChild(f);f.click();g.removeChild(f)});b.h("runtime","raster-svg-image",c=>Ba(c));b.h("runtime","get-svg-image-size",c=>Ca(c));b.h("runtime","set-target-orientation",c=>{this.Aa=c.targetOrientation});b.h("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.h("runtime",
"post-to-debugger",c=>Da(c));b.h("runtime","go-to-script",c=>Da(c));b.h("runtime","before-start-ticking",()=>Ea(this));b.h("runtime","debug-highlight",c=>{if(c.show){this.D||(this.D=document.createElement("div"),this.D.id="inspectOutline",document.body.appendChild(this.D));var e=this.D;e.style.display="";e.style.left=c.left-1+"px";e.style.top=c.top-1+"px";e.style.width=c.width+2+"px";e.style.height=c.height+2+"px";e.textContent=c.name}else this.D&&(this.D.style.display="none")});b.h("runtime","enable-device-orientation",
()=>Fa(this));b.h("runtime","enable-device-motion",()=>Ga(this));b.h("runtime","add-stylesheet",c=>Ia(c));b.h("runtime","script-create-worker",c=>{const e=c.port2;(new Worker(c.url,c.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});b.h("runtime","alert",c=>{alert(c.message)});b.h("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.h("runtime","set-exporting-to-video",c=>{this.l=!0;const e=document.createElement("h1");
e.id="exportToVideoMessage";e.textContent=c.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.i.j.style.display="";this.i.lb()});b.h("runtime","export-to-video-progress",c=>Ja(this,c));b.h("runtime","exported-to-video",c=>{window.Mb({type:"exported-video",blob:c.blob,time:c.time})});b.h("runtime","exported-to-image-sequence",c=>{window.Mb({type:"exported-image-sequence",blobArr:c.blobArr,time:c.time,gif:c.gif})});const a=new Set(["input","textarea","datalist"]);
window.addEventListener("contextmenu",c=>{const e=c.target;a.has(e.tagName.toLowerCase())||N(e)||c.preventDefault()});const d=b.j;window.addEventListener("selectstart",O);window.addEventListener("gesturehold",O);d.addEventListener("selectstart",O);d.addEventListener("gesturehold",O);window.addEventListener("touchstart",O,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",O,{passive:!1}),d.addEventListener("pointerdown",O)):d.addEventListener("touchstart",O);this.V=
0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",Aa,{passive:!1});window.addEventListener("wheel",Aa,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.l&&this.Va){var c=this.A();var e=this.u();if(this.i.Ia()){if(this.Ua){if(this.wa===c&&e<this.T){this.Y=this.T-e;Y(this,this.T,this.Y);c=void 0;break a}0<this.Y&&(this.Y=0,Y(this,e,this.Y))}this.wa=c;this.T=e}l(this,"window-resize",{innerWidth:c,innerHeight:e,devicePixelRatio:window.devicePixelRatio,
isFullscreen:J.N()});this.i.ka()&&(-1!==this.J&&clearTimeout(this.J),Na(this,c,e,0))}c=void 0}return c});window.addEventListener("fullscreenchange",()=>R(this));window.addEventListener("webkitfullscreenchange",()=>R(this));window.addEventListener("mozfullscreenchange",()=>R(this));window.addEventListener("fullscreenerror",c=>S(this,c));window.addEventListener("webkitfullscreenerror",c=>S(this,c));window.addEventListener("mozfullscreenerror",c=>S(this,c));if(b.ka())if(window.visualViewport){let c=
Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>c&&(document.scrollingElement.scrollTop=0);c=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var c=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));c="textarea"===c?!0:"input"===c?e.has(f.type.toLowerCase()||"text"):N(f)}else c=!1}c||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=c=>{"entered-fullscreen"===
c?(J.Pa(!0),R(this)):"exited-fullscreen"===c?(J.Pa(!1),R(this)):console.warn("Unknown wrapper message: ",c)};this.ya=new Set;this.Jb=new WeakSet;this.Hb=!1}Ea(){window.addEventListener("focus",()=>{l(this,"window-focus",null,L)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(d){a=!1}l(this,"window-blur",{parentHasFocus:a},L);this.V=0});window.addEventListener("focusin",a=>{a=a.target;(ya.has(a.tagName.toLowerCase())||N(a))&&l(this,"keyboard-blur",
null,L)});window.addEventListener("keydown",a=>La(this,"keydown",a));window.addEventListener("keyup",a=>La(this,"keyup",a));window.addEventListener("dblclick",a=>T(this,"dblclick",a,K));window.addEventListener("wheel",a=>{this.l||l(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.o,pageX:a.pageX,pageY:a.pageY+this.o,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},K)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",a=>{U(a);
V(this,"pointerdown",a)}),this.i.v&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.W=new self.kb(()=>{V(this,"pointermove",this.G);this.G=null}),this.W.Ta=!0,window.addEventListener("pointerrawupdate",a=>{this.G&&(this.fa+=this.G.movementX||0,this.ga+=this.G.movementY||0);this.G=a;a=this.W;if(-1===a.K){var d=Date.now(),c=d-a.da,e=a.Gb;c>=e&&a.Ta?(a.da=d,a.R=!0,a.Sa(),a.R=!1):a.K=self.setTimeout(a.Lb,Math.max(e-c,4))}})):window.addEventListener("pointermove",a=>V(this,"pointermove",
a)),window.addEventListener("pointerup",a=>V(this,"pointerup",a)),window.addEventListener("pointercancel",a=>V(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{U(a);W(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>W(this,"pointermove",a)),window.addEventListener("mouseup",a=>W(this,"pointerup",a)),window.addEventListener("touchstart",a=>{U(a);X(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>X(this,"pointermove",a)),window.addEventListener("touchend",
a=>X(this,"pointerup",a)),window.addEventListener("touchcancel",a=>X(this,"pointercancel",a)));const b=()=>this.ra();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.i.fb()&&!this.i.Ia()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{Y(this,this.u(),
navigator.virtualKeyboard.boundingRect.height)}))}A(){return this.i.A()}u(){return this.i.u()}ra(){var b=[...this.ya];this.ya.clear();if(!this.Hb)for(const a of b)(b=a.play())&&b.catch(()=>{this.Jb.has(a)||this.ya.add(a)})}});"use strict";
async function ja(b){if(b.Fb)throw Error("already initialised");b.Fb=!0;var a=b.C.qa(("playable-ad"===b.C.g?b.C.I:"")+"dispatchworker.js");b.sa=await b.C.ja(a,b.O,{name:"DispatchWorker"});a=new MessageChannel;b.ua=a.port1;b.sa.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.za=await na(b)}function ka(b){return[b.ua,b.za]}
async function na(b){const a=b.Za.length;var d=b.C.qa(("playable-ad"===b.C.g?b.C.I:"")+"jobworker.js");d=await b.C.ja(d,b.O,{name:"JobWorker"+a});const c=new MessageChannel,e=new MessageChannel;b.sa.postMessage({type:"_addJobWorker",port:c.port1},[c.port1]);d.postMessage({type:"init",number:a,"dispatch-port":c.port2,"output-port":e.port2},[c.port2,e.port2]);b.Za.push(d);return e.port1}
self.ib=class{constructor(b){this.C=b;this.O=b.m;this.O="preview"===b.g?this.O+"workers/":this.O+b.I;this.Ib=Math.min(navigator.hardwareConcurrency||2,16);this.sa=null;this.Za=[];this.za=this.ua=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.ma({Wb:!1,Xb:"workermain.js",M:["scripts/c3runtime.js"],ha:[],Ba:"",Tb:"scripts/",Ca:[],ab:"html5"}));"use strict";function Z(b){b.stopPropagation()}
self.ma.Da(class extends self.cb{constructor(b){super(b)}Ga(b,a){const d=document.createElement("input");var c=d;a.isCheckbox?(d.type="checkbox",c=document.createElement("label"),c.appendChild(d),c.appendChild(document.createTextNode("")),c.style.fontFamily="sans-serif",c.style.userSelect="none",c.style.webkitUserSelect="none",c.style.display="inline-block",c.style.color="black"):d.type="button";c.style.position="absolute";c.addEventListener("pointerdown",Z);c.addEventListener("pointermove",Z);c.addEventListener("pointerrawupdate",
Z);c.addEventListener("pointerup",Z);c.addEventListener("mousedown",Z);c.addEventListener("mouseup",Z);c.addEventListener("keydown",Z);c.addEventListener("keyup",Z);d.addEventListener("click",()=>{var e={isChecked:d.checked};e.elementId=b;p(this,"click",e)});a.id&&(d.id=a.id);a.className&&(d.className=a.className);this.na(c,a);return c}pa(b){return"input"===b.tagName.toLowerCase()?b:b.firstChild}na(b,a){const d="input"===b.tagName.toLowerCase()?b:b.firstChild;d.checked=a.isChecked;d.disabled=!a.isEnabled;
b.title=a.title;b===d?d.value=a.text:b.lastChild.textContent=a.text}});
